### ISSUE TITLE
Union of intervals, merging intervals improvements

### ISSUE THREAD

**Issue by doriath2006** [Breinify/brein-time-utilities#9]
It would be nice to implement some other operations on intervals like union, disjoints, etc..

Merging (union) can be similar to following one:
https://gist.github.com/zac-xin/4349436

**Comment by pmeisen** [comment]
Hi Doriath,

thanks for the feedback and the enhancement request. The main issue with your request is that the mentioned operations like union or disjoints do not really exist for intervals (as interval based operations). What you are mentioning are set operation. I know that every interval is a set, but not every set is an interval and the latter is exactly the problem. The operations that you mention have a set as result and not necessarily and interval, `union(interval1, interval2) -> set` and this set is a mathematical set and not the Java collection `Set` (this is especially true if we are dealing with open intervals over the real numbers (e.g., `union( [1.2, 3.7), (10.2, 6.2) ] = ?`).

All that said, here the positive news 😄  :
I also looked at the implementation you mention as an example. This example would assume these operations are applied on a `Collection` of intervals and return a `Collection` of such. If we allow that it can be implemented so that `union( {[1.2, 3.7), (10.2, 6.2)} ] = {[1.2, 3.7], [10.2, 6.2]}`, but the benefit of such an implementation would only be really given if the containing intervals `overlap` in some way. 

Let me know if the latter is what you are looking for, i.e., operations on collections of intervals and maybe provide a use-case to understand the need of these operations a little bit more.

**Comment by pmeisen** [comment]
I'll close this request for now since there was no response for a while.

**Comment by sasconsul** [comment]
The intervals can also abut to make it useful.  The primary use will be outside of the time domain.  Merging is very useful for geographic and other types of intervals.
